apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ybm3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ybm3
    app.kubernetes.io/part-of: ci1t-830-0022-app
  name: devfile-sample-ybm3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ybm3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ybm3
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0022-tenant/ci1t-830-0022-app/devfile-sample-ybm3@sha256:77c1e8f81a3b3dba060dbd415e58fd81f20f53da124a472c1ef810d0aecc230e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
